repos:
  - repo: local
    hooks:
      - id: lint
        name: Linting
        entry: just lint
        language: system
        always_run: true
        pass_filenames: true
        types: [python]
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: just mypy
        language: system
        always_run: true
        pass_filenames: true
        types: [python]
