repos:
  - repo: local
    hooks:
      - id: lint
        name: Linting
        entry: just lint
        language: system
        pass_filenames: true
        exclude: ca_cdk_constructs/eks/imports/
        types: [python]
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        entry: just mypy
        language: system
        pass_filenames: true
        exclude: ca_cdk_constructs/eks/imports/
        types: [python]
