name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v2

      - uses: citizensadvice/python-poetry-setup-action@v1
        with:
          python_version: ${{ matrix.python_version }}

      - name: Run tests
        run: poetry run pytest -vv
