name: Tests

on: pull_request

jobs:
  typecheck:
    name: MyPy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v3
      - uses: citizensadvice/python-uv-setup-action@v1
        with:
          python_version: 3.13
      - name: Run type check
        run: just mypy

  test:
    name: Testing on python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v2
      - uses: citizensadvice/python-uv-setup-action@v1
        with:
          python_version: ${{ matrix.python_version }}
      - run: just lint
      - run: just pytest

  checks-successful:
    name: All Checks Passed
    runs-on: ubuntu-latest
    if: always()
    needs: [typecheck, test]
    steps:
      - uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
