name: test

on: pull_request

jobs:
  ruff:
    name: Ruff ${{ matrix.action.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - name: check
            cmd: check
          - name: format
            cmd: format --check
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruff
        run: pip3 install ruff==0.1.5 # Must match version pinned in .pre-commit.yaml
      - name: Ruff ${{ matrix.action.name }}
        run: ruff ${{ matrix.action.cmd }} .

  typecheck:
    name: Running type check
    continue-on-error: true # Run as a warning rather than an error at this stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: citizensadvice/python-poetry-setup-action@v1
        with:
          python_version: 3.12
      - name: Run type check
        run: poetry run mypy . 

  tests:
    name: Testing on python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    needs: ruff
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - uses: citizensadvice/python-poetry-setup-action@v1
        with:
          python_version: ${{ matrix.python_version }}
      - name: Run tests
        run: poetry run pytest -vv


  test:
    # Single job for github to expect. Any merge-blocking checks should be added to the needs array
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - run: exit 1
        if: ${{contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')}}
