name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: citizensadvice/python-poetry-setup-action@v1

      - name: Run tests
        run: |
          poetry run pytest tests/
